// <auto-generated />
using System;
using BarSplitterMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarSplitterMVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231203222545_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarSplitterMVC.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double?>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PrendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrendaId");

                    b.ToTable("Jogo");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioAdminId")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAdminId");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Conta")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("JogoId")
                        .HasColumnType("int");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("JogoId");

                    b.HasIndex("MesaId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Grupo", b =>
                {
                    b.HasOne("BarSplitterMVC.Models.Mesa", null)
                        .WithMany("Grupos")
                        .HasForeignKey("MesaId");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Item", b =>
                {
                    b.HasOne("BarSplitterMVC.Models.Mesa", null)
                        .WithMany("Itens")
                        .HasForeignKey("MesaId");

                    b.HasOne("BarSplitterMVC.Models.Usuario", null)
                        .WithMany("Itens")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Jogo", b =>
                {
                    b.HasOne("BarSplitterMVC.Models.Item", "Prenda")
                        .WithMany()
                        .HasForeignKey("PrendaId");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Mesa", b =>
                {
                    b.HasOne("BarSplitterMVC.Models.Usuario", "UsuarioAdmin")
                        .WithMany()
                        .HasForeignKey("UsuarioAdminId");

                    b.Navigation("UsuarioAdmin");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Usuario", b =>
                {
                    b.HasOne("BarSplitterMVC.Models.Grupo", null)
                        .WithMany("IntegrantesGrupo")
                        .HasForeignKey("GrupoId");

                    b.HasOne("BarSplitterMVC.Models.Jogo", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("JogoId");

                    b.HasOne("BarSplitterMVC.Models.Mesa", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("MesaId");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Grupo", b =>
                {
                    b.Navigation("IntegrantesGrupo");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Jogo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Mesa", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Itens");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BarSplitterMVC.Models.Usuario", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
